app_flask/models/book.py
from app_flask import db

class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text, nullable=False)
    text = db.Column(db.Text, nullable=False)
    cover_photo = db.Column(db.String(255))  # URL de la foto de portada
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False, unique=False)
    user = db.relationship('User', backref=db.backref('books', lazy=True))

app_flask/models/reservations.py
from app_flask import db

class Reservation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    book_id = db.Column(db.Integer, db.ForeignKey('book.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('reservations', lazy=True))
    book = db.relationship('Book', backref=db.backref('reservations', lazy=True))

app_flask/models/user.py
from app_flask import db, login_manager
from flask_login import UserMixin

login_manager

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    is_special = db.Column(db.Boolean, default=False)  # Indica si el usuario es especial

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app_flask/__init__.py
# __init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

# Inicialización de SQLAlchemy y LoginManager fuera de la función create_app()
db = SQLAlchemy()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)
    app.config.from_object('config')
    
    # Asociar db y login_manager con la aplicación Flask
    db.init_app(app)
    login_manager.init_app(app)
    
    with app.app_context():
        db.create_all()
    
    from app_flask.routes.main import main
    from app_flask.routes.auth import auth
    from app_flask.routes.books import books
    from app_flask.routes.dashboard import dashboard
    app.register_blueprint(main)
    app.register_blueprint(auth)
    app.register_blueprint(books)
    app.register_blueprint(dashboard)

    return app

app_flask/routes/auth.py
from flask import Blueprint, request, render_template, jsonify, redirect, url_for, make_response
from flask_login import login_user, login_required, logout_user
from app_flask.models.user import User, db

auth = Blueprint('auth', __name__, template_folder='../templates')

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET': 
        return render_template('auth/signup.html')
    elif request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User(username=username, password=password)
        existingUser = User.query.filter_by(username=username).first()

        if existingUser:
            return jsonify({'error': 'El usuario ya existe'}), 400
        
        if User.query.count() == 0: 
            user.is_special = True

        db.session.add(user)
        db.session.commit()

        login_user(user)
        return jsonify({'success': True}), 200  # Devuelve una respuesta JSON de éxito
    
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET': 
        return render_template('auth/login.html')
    else: 
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()

        if not user or not user.password == password: 
            return jsonify({'error': 'Usuario o contraseña incorrectos'}), 400

        login_user(user)
        return jsonify({'success': True}), 200  # Devuelve una respuesta JSON de éxito
        
@login_required
@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

app_flask/routes/books.py
from flask import Blueprint, render_template, redirect, url_for, request
from app_flask.models.book import Book
from app_flask import db
from flask_login import login_required, login_required, current_user

books = Blueprint('books', __name__, template_folder='../templates')

@books.route('/books', methods=['GET', 'POST'])
@login_required
def all_books(): 
    return render_template('books/books.html', books=Book.query.all())

@books.route('/create-books', methods=['GET', 'POST'])
@login_required
def create_books():
    if not current_user.is_special: 
        return redirect(url_for('main.home', error='Login with a Admin Account'))
    if request.method == 'GET': 
        return render_template('books/create-books.html')
    else: 
        name = request.form.get('name')
        description = request.form.get('description')
        text = request.form.get('text') 
        cover_photo = request.form.get('cover_photo')
        book = Book(name=name, description=description, text=text, cover_photo=cover_photo, user_id=current_user.id) 
        db.session.add(book)
        db.session.commit()
        return redirect(url_for('books.all_books'))

@books.route('/delete-book/<int:book_id>', methods=['GET', 'POST'])
@login_required
def delete_book(book_id):
    if not current_user.is_special: 
        return redirect(url_for('main.home', error='Login with a Admin Account'))
    else: 
        book = Book.query.get_or_404(book_id)
        db.session.delete(book)
        db.session.commit()
        return redirect(url_for('books.all_books'))

app_flask/routes/dashboard.py
from flask import Blueprint, redirect, url_for, render_template, Response
from flask_login import login_required, current_user
from app_flask.models.book import Book
from app_flask.models.reservations import Reservation
from app_flask.utils.create_pdf import create_pdf
from app_flask import db

dashboard = Blueprint('dashboard', __name__, template_folder='../templates')

@dashboard.route('/reserve_book/<int:book_id>', methods=['GET', 'POST'])
@login_required
def reserve_book(book_id):
    book = Book.query.get_or_404(book_id)
    existing_reservation = Reservation.query.filter_by(user_id=current_user.id).first()
    if existing_reservation:
        return redirect(url_for('dashboard.my_dashboard', error='Ya has reservado un libro. No puedes reservar más de un libro.'))
    reservation = Reservation(user_id=current_user.id, book_id=book.id)
    db.session.add(reservation)
    db.session.commit()
    return redirect(url_for('dashboard.my_dashboard'))

@dashboard.route('/delete-reservation/<int:reservation_id>', methods=['GET', 'POST'])
@login_required
def delete_reservation(reservation_id):
    # Buscar la reserva por su ID
    reservation = Reservation.query.get_or_404(reservation_id)
    
    # Verificar si la reserva pertenece al usuario actual
    if reservation.user_id!= current_user.id:
        return redirect(url_for('main.home', error='No tienes permiso para eliminar esta reserva.'))

    # Eliminar la reserva de la base de datos
    db.session.delete(reservation)
    db.session.commit()

    # Redirigir al usuario a la página principal
    return redirect(url_for('main.home'))

@dashboard.route('/dashboard', methods=['GET', 'POST'])
@login_required
def my_dashboard(): 
    reservations = Reservation.query.filter_by(user_id=current_user.id).all()
    # Obtiene los libros correspondientes a las reservaciones
    books = [reservation.book for reservation in reservations]
    return render_template('dashboard/dashboard.html', books=books)

@dashboard.route('/download_book/<int:book_id>', methods=['GET', 'POST'])
@login_required
def download_book(book_id):
    book = Book.query.get_or_404(book_id)
    pdf_buffer = create_pdf(book)
    response = Response(pdf_buffer.getvalue(), mimetype='application/pdf')
    response.headers.set('Content-Disposition', f'attachment; filename={book.name}.pdf')
    return response

app_flask/routes/main.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__, template_folder='../templates')  # Asegúrate de especificar el directorio de templates si es necesario

@main.route('/')
def home():
    return render_template('auth/home.html') # app_flask/templates/auth/home.html

app_flask/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca Flask y Bootstrap</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/6e3a2cfd19.js" crossorigin="anonymous"></script>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Book Sell</a>
        </div>
        <div class="collapse navbar-collapse justify-content-center">

            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('dashboard.my_dashboard') }}">Dashboard</a></li>
                <li><a href="{{ url_for('books.all_books') }}">Books</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>

                {% if current_user.is_special %}
                <li><a href="{{ url_for('books.create_books') }}">Create books</a></li>
                {% endif %}

                {% else %}
                <li><a href="{{ url_for('main.home') }}">Home</a></li>
                <li><a href="{{ url_for('auth.signup') }}">Signup</a></li>
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>

                {% endif %}
            </ul>
        </div>
  </div>
</nav>


<div class="container mt-5"> <!-- Aquí se agrega el margen superior -->
    {% block content %}
    <!-- Contenido aquí -->
    {% endblock %}
</div>


</body>
</html>

app_flask/templates/books/books.html
{% extends 'base.html'%}
{% block content %}

{% for book in books %}
<div class="container mt-5" style="margin-top: 100px;">
    <div class="card mb-4">
        <img src="{{ book.cover_photo }}" alt="Cover Photo" class="card-img-top">
        <div class="card-body">
            <h2 class="card-title">{{ book.name }}</h2>
            <p class="card-text">{{ book.description }}</p>
            <button class="btn btn-primary" onclick="reserveBookButtonClick('{{ book.id }}')">Reservar</button>

            {% if current_user.is_special %}
            <button class="btn btn-danger" onclick="deleteBookButtonClick('{{ book.id }}')">Eliminar el libro</button>
            {% endif %}
            
        </div>
    </div>
</div>

{% endfor %}

<script>
    function deleteBookButtonClick(book_id) {
        window.location.href = `delete-book/${book_id}`;
        console.info('Book deleted successfully')
    }

    function reserveBookButtonClick(book_id) {
        window.location.href = `reserve_book/${book_id}`;
        console.info('Book deleted successfully')
    }
    
</script>
{% endblock content %}

app_flask/templates/books/create-books.html
{% extends 'base.html'%}
{% block content %}
    <div class="container mt-5" style="margin-top: 100px;">
        <h2>Crear Libro</h2>
        
        <form action="{{ url_for('books.create_books') }}" method="POST" class="form-horizontal">
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Nombre del libro:</label>
                <div class="col-sm-10">
                    <input type="text" name="name" id="name" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label for="description" class="col-sm-2 control-label">Descripción del libro:</label>
                <div class="col-sm-10">
                    <textarea name="description" id="description" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="text" class="col-sm-2 control-label">Texto del libro:</label>
                <div class="col-sm-10">
                    <textarea name="text" id="text" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="cover_photo" class="col-sm-2 control-label">URL de la foto de portada:</label>
                <div class="col-sm-10">
                    <input type="text" name="cover_photo" id="cover_photo" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Crear libro</button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <p id="errorMensage" class="text-3xl text-danger font-custom">{{ error }}</p>                    
                </div>
            </div>
        </form>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const form = document.querySelector('form');
            const errorMensageElement = document.getElementById('errorMensage'); // Obtén el elemento directamente
        
            form.addEventListener('submit', (e) => {
                e.preventDefault(); // Evita que el formulario se envíe por defecto
        
                let name = document.getElementById('name').value;
                let description = document.getElementById('description').value;
                let text = document.getElementById('text').value;
                let cover_photo = document.getElementById('cover_photo').value;
        
                if (name.length < 10 || description.length < 10 || text.length < 10 || cover_photo.length < 10) {
                    if (errorMensageElement) { // Verifica si el elemento existe antes de intentar cambiar su textContent
                        errorMensageElement.textContent = 'Por favor ingresa los caracteres mínimos'; // Establece el mensaje de error
                        console.log(name.length, description.length, text.length, cover_photo.length)
                        console.log(name, description, text, cover_photo)
                    }
                } else {
                    // Envía el formulario si todos los campos cumplen con los requisitos
                    form.submit(); // Utiliza el método submit() para enviar el formulario
                }
            });
        });
        
    </script>
{% endblock content %}

app_flask/templates/dashboard/dashboard.html
{% extends 'base.html'%}
{% block content %}

<div class="container mt-5" style="margin-top: 100px;">
    <h1>Libros reservados</h1>
    <div class="row">
        {% for book in books %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ book.cover_photo }}" alt="{{ book.name }}" class="card-img-top">
                    <div class="card-body">
                        <h2 class="card-title">{{ book.name }}</h2>
                        <p class="card-text">{{ book.description }}</p>
                        <p class="card-text">{{ book.text }}</p>
                        <a href="{{ url_for('dashboard.download_book', book_id=book.id) }}" download class="btn btn-primary">Descargar PDF</a>
                        <button class="btn btn-danger" onclick="deleteReservation('{{ book.id }}')">Eliminar la reservacion</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<script>
    function deleteReservation(book_id) {
        window.location.href = `delete-reservation/${book_id}`;
        console.info('Book deleted successfully')
    }

</script>

{% endblock content %}